ignore:
  - src/valgrind/
  - src/sys/
  - doc/
  - examples/
  - utils/
  - tests/

comment:
  layout: "diff"
  behavior: default
  require_changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: false
      loop: false
      method: false
      macro: false
