#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2020, Intel Corporation
#

#
# Dockerfile - a 'recipe' for Docker to build an image of ubuntu-based
#              environment prepared for running rpma tests.
#

# Pull base image
FROM ubuntu:18.04
MAINTAINER tomasz.gromadzki@intel.com

ENV DEBIAN_FRONTEND noninteractive

# Additional parameters to build docker without building components
ARG SKIP_SCRIPTS_DOWNLOAD

# Update the Apt cache and install basic tools
RUN apt-get update && apt-get dist-upgrade -y

# base deps
ENV BASE_DEPS "\
	apt-utils \
	build-essential \
	ca-certificates \
	devscripts \
	git \
	pkg-config \
	sudo \
	whois"

ENV EXAMPLES_DEPS "\
	libpmem-dev"

# RPMA deps
ENV RPMA_DEPS "\
	cmake \
	curl \
	gawk \
	groff \
	graphviz \
	libibverbs-dev \
	librdmacm-dev \
	libunwind-dev"
#	txt2man is installed from git repo now

# Install all required packages
RUN apt-get install -y --no-install-recommends \
	$BASE_DEPS \
	$EXAMPLES_DEPS \
	$RPMA_DEPS \
&& rm -rf /var/lib/apt/lists/*

# Install cmocka
COPY install-cmocka.sh install-cmocka.sh
RUN ./install-cmocka.sh

# Install txt2man
COPY install-txt2man.sh install-txt2man.sh
RUN ./install-txt2man.sh

# Download scripts required in run-*.sh
COPY download-scripts.sh download-scripts.sh
COPY 0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch 0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch
RUN ./download-scripts.sh

# Add user
ENV USER user
ENV USERPASS pass
RUN useradd -m $USER -g sudo -p `mkpasswd $USERPASS`
USER $USER

# Set required environment variables
ENV OS ubuntu
ENV OS_VER 18.04
ENV PACKAGE_MANAGER deb
ENV NOTTY 1
