#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2023, Intel Corporation
#

#
# Dockerfile.fedora-latest-with-rdma-core-45 - Dockerfile for Fedora-latest with rdma-core v45.0
#                                              installed from sources.
#
# This dockerfile is a 'recipe' for Docker to build an image of fedora-based environment
# prepared for running tests of librpma.
#

# Pull base image
FROM fedora:latest
MAINTAINER tomasz.gromadzki@intel.com

# Update all packages
RUN dnf update -y

# base Linux deps
ENV BASE_DEPS "\
	clang \
	gcc \
	git \
	make \
	patch \
	pkg-config \
	rpm-build \
	which"

# librpma library deps
ENV RPMA_DEPS "\
	cmake \
	file \
	gawk \
	groff \
	graphviz \
	pandoc"

# examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
ENV EXAMPLES_DEPS "\
	libpmem-devel \
	libpmem2-devel \
	protobuf-c-devel"

# doc update deps
ENV DOC_UPDATE_DEPS "\
	hub"

# rdma-core built from sources deps
ENV RDMA_CORE_FROM_SOURCES_DEPS "\
	libnl3-devel \
	wget"

# Install all required packages
RUN dnf install -y \
	$BASE_DEPS \
	$RPMA_DEPS \
	$EXAMPLES_DEPS \
	$DOC_UPDATE_DEPS \
	$RDMA_CORE_FROM_SOURCES_DEPS \
&& dnf clean all

# Install rdma-core
COPY install-rdma-core.sh install-rdma-core.sh
RUN ./install-rdma-core.sh

# Install cmocka
COPY install-cmocka.sh install-cmocka.sh
RUN ./install-cmocka.sh

# Install txt2man
COPY install-txt2man.sh install-txt2man.sh
RUN ./install-txt2man.sh

# Add user
ENV USER user
ENV USERPASS p1a2s3s4
RUN useradd -m $USER
RUN echo "$USER:$USERPASS" | chpasswd
RUN gpasswd wheel -a $USER
USER $USER

# Set required environment variables
ENV OS fedora
ENV OS_VER latest
ENV PACKAGE_MANAGER rpm
ENV NOTTY 1
# Paths to the rdma-core built from sources
ENV PKG_CONFIG_PATH /rdma-core/build/lib/pkgconfig
ENV LIBRARY_PATH /rdma-core/build/lib
ENV LD_LIBRARY_PATH /rdma-core/build/lib
ENV CPATH /rdma-core/build/include
