#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation
#

#
# Dockerfile - a 'recipe' for Docker to build an image of ubuntu-based
#              environment prepared for running libpmemobj-cpp tests.
#

# Pull base image
FROM archlinux/base:latest
MAINTAINER tomasz.gromadzki@intel.com

# Do full system upgrade
RUN pacman -Syu --noconfirm

# base deps
ENV BASE_DEPS "\
	gcc \
	git \
	make \
	pkg-config \
	sudo \
	which"

# rdma-core deps
ENV RDMA_DEPS "\
	fakeroot \
	file"

# RPMA deps
ENV RPMA_DEPS "\
	cmake \
	diffutils \
	file \
	gawk \
	groff \
	graphviz \
	libunwind"

# Install required packages
RUN pacman -S --noconfirm \
	$BASE_DEPS \
	$RDMA_DEPS \
	$RPMA_DEPS

# Install cmocka
COPY install-cmocka.sh install-cmocka.sh
RUN ./install-cmocka.sh

# Install txt2man
COPY install-txt2man.sh install-txt2man.sh
RUN ./install-txt2man.sh

# Add user
ENV USER user
ENV USERPASS p1a2s3s4
ENV PFILE ./password
RUN useradd -m $USER
RUN echo $USERPASS > $PFILE
RUN echo $USERPASS >> $PFILE
RUN passwd $USER < $PFILE
RUN rm -f $PFILE
RUN sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers
RUN gpasswd wheel -a $USER

# Enable preserving given variables in the privileged environment -
# - it is required by 'makepkg' to download required packages and sources
RUN echo 'Defaults env_keep += "ftp_proxy http_proxy https_proxy no_proxy"' >> /etc/sudoers
RUN echo 'Defaults env_keep += "FTP_PROXY HTTP_PROXY HTTPS_PROXY NO_PROXY"' >> /etc/sudoers

# Install rdma-core (requires user 'user')
COPY install-archlinux-aur.sh install-archlinux-aur.sh
RUN ./install-archlinux-aur.sh rdma-core

# Switch to user
USER $USER

# Clean the cache of packages
RUN rm -rf /var/cache/pacman/pkg/*

# Set required environment variables
ENV OS archlinux-base
ENV OS_VER latest
ENV PACKAGE_MANAGER none
ENV NOTTY 1
