#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020-2022, Intel Corporation
#

#
# Dockerfile - a 'recipe' for Docker to build an image of RedHat-based
#              environment prepared for running tests of librpma.
#

# Pull base image
FROM rockylinux/rockylinux:8.4
MAINTAINER tomasz.gromadzki@intel.com

RUN dnf update -y
RUN dnf install -y epel-release
RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled powertools

# base Linux deps
ENV BASE_DEPS "\
	clang \
	gcc \
	git \
	make \
	passwd \
	pkg-config \
	rpm-build \
	sudo \
	which"

# librpma library deps
ENV RPMA_DEPS "\
	cmake \
	diffutils \
	file \
	gawk \
	groff \
	graphviz \
	pandoc \
	rdma-core-devel"

# performance tools deps
ENV TOOLS_DEPS "\
	python3-jinja2 \
	python3-pylint \
	python3-pip \
	python3-pytest"

# performance tools python deps
ENV TOOLS_PYTHON_DEPS "\
	coverage \
	deepdiff \
	markdown2 \
	matplotlib \
	paramiko \
	pylint \
	scp"

# PMDK deps
ENV PMDK_DEPS "\
	ndctl \
	wget"

# Install all required packages
RUN dnf install -y \
	$BASE_DEPS \
	$RPMA_DEPS \
	$TOOLS_DEPS \
	$PMDK_DEPS \
&& dnf clean all

RUN pip3 install --upgrade pip

# Install cmocka
COPY install-cmocka.sh install-cmocka.sh
RUN ./install-cmocka.sh

# Install txt2man
COPY install-txt2man.sh install-txt2man.sh
RUN ./install-txt2man.sh

# Install PMDK
COPY install-pmdk.sh install-pmdk.sh
RUN ./install-pmdk.sh

# Add user
ENV USER user
ENV USERPASS p1a2s3s4
RUN useradd -m $USER
RUN echo $USERPASS | passwd $USER --stdin
RUN gpasswd wheel -a $USER
USER $USER

# Set required environment variables
ENV OS rockylinux/rockylinux
ENV OS_VER 8.4
ENV PACKAGE_MANAGER rpm
ENV NOTTY 1

# install python modules for the default user
RUN pip3 install --user $TOOLS_PYTHON_DEPS
